spring.application.name=gerencia-veiculos
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=always
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.jpa.hibernate.ddl-auto=none
