CREATE TABLE IF NOT EXISTS veiculos (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        placa VARCHAR(10) NOT NULL,
    marca VARCHAR(50),
    cor VARCHAR(50),
    ano INT,
    preco_usd DECIMAL(19,2),
    ativo BOOLEAN DEFAULT TRUE
    );